name: Dataverse Upload Workflow

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send repo to Dataverse 
        uses: EdoardoCostantini/dataverse-uploader@1-add-the-option-to-submit-for-review
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://demo.dataverse.nl
          DATAVERSE_DATASET_DOI: doi:10.80227/PDVNL/KQ301R
          DELETE: TRUE
          REVIEW: TRUE
